name: CI

on:
  push:
    branches: [main, master, release-candidate]
  pull_request:
    branches: [main, master, release-candidate]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v4

      - name: install dev
        run: ./.dev/bin/dev install

      - name: run ci
        run: ./.dev/bin/dev ci

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v4

      - name: install dev
        run: ./.dev/bin/dev language set rust && ./.dev/bin/dev install

      - name: run ci
        run: cd src-tauri && ../.dev/bin/dev ci
